name: conectivity test
description: connectivity test
inputs:
  test-string:
    description: test string
    required: true
    default: connectedprakask
outputs:
  random-number:
    description: random number
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: composite
  steps:
    - name: echo string
      run: echo "$INPUT_STRING"
      shell: bash
      env:
        INPUT_STRING: ${{ inputs.test-string }}

    - name: random number
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: set github path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: run complete.sh
      run: complete.sh
      shell: bash

